export const authconstants = {
    
    PAGE_CHANGE: 'PAGE_CHANGE',
   
};
export const registerconstants = {
   
    USER_RESET: 'USER_RESET',
    SET_USER_SEARCHFIELD: 'SET_USER_SEARCHFIELD',
    SET_FILTER: 'SET_FILTER',
    SET_DATE_FILTER: 'SET_DATE_FILTER',
    REMOVE_DATE_FILTER: 'REMOVE_DATE_FILTER',
    REMOVE_FILTER : 'REMOVE_FILTER ',
    SET_ASK_USER: 'SET_ASK_USER',
    REMOVE_ASK_USER: 'REMOVE_ASK_USER'
};
export const dashboardconstants = {
    CATEGORY_LIST_REQUEST : 'CATEGORY_LIST_REQUEST',
    CATEGORY_LIST_SUCCESS : 'CATEGORY_LIST_SUCCESS',
    CATEGORY_LIST_FAILED : 'CATEGORY_LIST_FAILED',
 
  
  
    PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAILED : 'PRODUCT_LIST_FAILED',
   
  
    SET_OFFERS : 'SET_OFFERS',
    SET_CATEGORY_FILTER: 'SET_CATEGORY_FILTER'
};

export const cartconstants = {
    ADD_CART_REQUEST: 'ADD_CART_REQUEST',
    ADD_CART_SUCCESS: 'ADD_CART_SUCCESS',
    ADD_CART_FAILED: 'ADD_CART_FAILED',
    GET_CART_REQUEST: 'GET_CART_REQUEST',
    GET_CART_SUCCESS:'GET_CART_SUCCESS',
    GET_CART_FAILED: 'GET_CART_FAILED',
    DELETE_CARTITEM_REQUEST: 'DELETE_CARTITEM_REQUEST',
    DELETE_CARTITEM_SUCCESS: 'DELETE_CARTITEM_SUCCESS',
    DELETE_CARTITEM_FAILED: 'DELETE_CARTITEM_FAILED',
    CART_RESET: 'CART_RESET',
    ADJUST_QUANTITY: 'ADJUST_QUANTITY',
    UPDATE_CART_SUCCESS: 'UPDATE_CART_SUCCESS',

};
export const orderconstants = {
   
    SET_QUANTITY: 'SET_QUANTITY'
}